openrewrite/rewrite-static-analysis

src/test/java/org/openrewrite/staticanalysis/ExplicitInitializationTest.java

Add test with @ExpectedToFail
issue: https://github.com/openrewrite/rewrite-static-analysis/issues/101

ExplicitInitialization removes initialization from final fields when using @Value

---

src/main/java/org/openrewrite/staticanalysis/ExplicitInitializationVisitor.java
src/test/java/org/openrewrite/staticanalysis/ExplicitInitializationTest.java

fixes: https://github.com/openrewrite/rewrite-static-analysis/issues/101
Do not remove explicit init in case lombok.Value is present on enclosing class

Do not remove explicit init in case lombok.Value is present on enclosing class

---

src/main/java/org/openrewrite/staticanalysis/LambdaBlockToExpression.java
src/test/java/org/openrewrite/staticanalysis/LambdaBlockToExpressionTest.java

added a failing test for LambdaBlockToExpression
#1 
Not sure if the name of my unit test is okay
Still get myself familiar with LST, probably will have new discovery later

added a failing test for LambdaBlockToExpression

---

src/main/java/org/openrewrite/staticanalysis/RemoveJavaDocAuthorTag.java
src/test/java/org/openrewrite/staticanalysis/RemoveJavaDocAuthorTagTest.java

Check if the remaining JavaDoc lines are all blank after removing author tag.
Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/119
Usage of PrintOutputCapture & Cursor to check for blank lines; wasn't sure if there's any other mechanism.
We could pull `isBlank` into `JavaDoc`, if we want to also fix this for #98, which has a slightly broader scope: trim in addition to remove when fully empty.

Remove blank JavaDoc blocks after RemoveJavaDocAuthorTag

---

src/main/java/org/openrewrite/staticanalysis/RemoveHashCodeCallsFromArrayInstances.java
src/test/java/org/openrewrite/staticanalysis/RemoveHashCodeCallsFromArrayInstancesTest.java

This is related to [my other PR](https://github.com/openrewrite/rewrite-static-analysis/pull/126). @timtebeek suggested to me that I split the recipe because the `toString()` part required more checks since `toString()` is such a widely used method. This recipe basically does the same thing but on a smaller scale for `hashCode()` calls on array instances. 
[#44](https://github.com/openrewrite/rewrite-static-analysis/issues/44)
I think this recipe should be finished but maybe there are other edge case methods that implicitly call `hashCode()` I'm forgetting. 
@timtebeek 
[RSPEC-2116](https://rules.sonarsource.com/java/RSPEC-2116)

Remove hashCode calls on arrays

---

src/main/java/org/openrewrite/staticanalysis/JavaElementFactory.java
src/main/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReference.java
src/test/java/org/openrewrite/staticanalysis/JavaElementFactoryTest.java
src/test/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReferenceTest.java

Improves the type attribution for method references by "manually" instantiating the `J.MemberReference` rather than via `JavaTemplate`. This may seem strange, but the reason is that the recipe doesn't know where the type is coming from (JDK, 3rd party library, or even source path), so the template's compiler may not have the type on its classpath and cannot really produce a properly type-attributed result.

Better type attribution for `ReplaceLambdaWithMethodReference`

---

src/main/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReference.java
src/test/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReferenceTest.java

While applying the `CommonStaticAnalysis` [recipe](https://docs.openrewrite.org/recipes/staticanalysis/commonstaticanalysis) on our internal codebase, we found a false positive that results in non-compilable code.
This PR introduces a minimal reproduction case to show the problem. Probably the test case can be simplified even further.
If anything is unclear, let me know.
Depending on what the fix would be, I'm interested in contributing 😄.

`ReplaceLambdaWithMethodReference` should not replace lambda supplier of method reference with method reference

---

src/main/java/org/openrewrite/staticanalysis/FinalizePrivateFields.java
src/test/java/org/openrewrite/staticanalysis/FinalizePrivateFieldsTest.java

This PR fixes a bug having to do with the FinalizePrivateFields recipe adding the `final` flag to variables that also have the `volatile` flag which is invalid. 
[#121](https://github.com/openrewrite/rewrite-static-analysis/issues/121)
@timtebeek

Bug Fix for #121

---

build.gradle.kts
src/main/java/org/openrewrite/staticanalysis/StringLiteralEquality.java
src/main/java/org/openrewrite/staticanalysis/groovy/GroovyFileChecker.java
src/test/java/org/openrewrite/staticanalysis/groovy/StringLiteralEqualityTest.java

Add a `GroovyFileChecker` as precondition to `StringLiteralEquality`.
Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/140

Do not use String `equals` for Groovy either

---

src/main/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReference.java
src/test/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReferenceTest.java

`ReplaceLambdaWithMethodReference` should not replace ambiguous references

---

src/main/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariables.java
src/test/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariablesTest.java

Not guaranteed safe to delete constructor calls either.

Do not remove unused variables with constructor calls

---

src/main/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariables.java
src/test/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariablesTest.java

RemoveUnusedLocalVariables fails inside case blocks (test)

---

src/main/java/org/openrewrite/staticanalysis/BooleanChecksNotInverted.java
src/main/java/org/openrewrite/staticanalysis/RemoveToStringCallsFromArrayInstances.java
src/main/java/org/openrewrite/staticanalysis/ReplaceWeekYearWithYear.java
src/main/java/org/openrewrite/staticanalysis/SimplifyBooleanExpression.java
src/main/java/org/openrewrite/staticanalysis/SimplifyBooleanReturn.java
src/main/java/org/openrewrite/staticanalysis/SortedSetStreamToLinkedHashSet.java
src/main/java/org/openrewrite/staticanalysis/UnnecessaryExplicitTypeArguments.java
src/main/java/org/openrewrite/staticanalysis/UnnecessaryThrows.java

To improve clarity, grammar, and style.

Clean up some recipe descriptions

---

src/main/java/org/openrewrite/staticanalysis/EmptyBlockVisitor.java
src/test/java/org/openrewrite/staticanalysis/EmptyBlockTest.java

Try with resources can have side effects (closing the streams) even with empty try blocks. So we cannot delete it safely.
Modified the emptyTry test to not have resources (so it's removed because it's empty), and added a new emptyTryWithResources that is actually not removed because it has resources.
@kmccarp

do not remove try block if there are resources

---

src/main/java/org/openrewrite/staticanalysis/SimplifyBooleanReturn.java
src/test/java/org/openrewrite/staticanalysis/SimplifyBooleanReturnTest.java

No longer simplify boolean returns if there are comments on the return statements.
Comments might provide important context that can be lost when returns are simplified.

Do not simplify boolean return with comments

---

src/main/java/org/openrewrite/staticanalysis/InlineVariable.java
src/test/java/org/openrewrite/staticanalysis/InlineVariableTest.java

Before this PR we get a compiler error.
After this PR we retain the array for now.
A future PR might move the type declaration.

Preserve arrays when inlining variables

---

src/main/java/org/openrewrite/staticanalysis/UseCollectionInterfaces.java
src/test/java/org/openrewrite/staticanalysis/UseCollectionInterfacesTest.java

That changes the type of the generic, potentially breaking iterators.
Fixes #179
Exclude EnumSet from the recipe.
I've not commented in the recipe but rather created a unit test to verify that EnumSet doesn't get back into the recipe on accident.

Don't redeclare EnumSet as Set

---

src/main/java/org/openrewrite/staticanalysis/FinalizeLocalVariables.java
src/test/java/org/openrewrite/staticanalysis/FinalizeLocalVariablesTest.java

Variables identified as fields of anonymous classes will be skipped in **FinalizeLocalVariables** recipe.
Fixes #181 
There is perhaps a better way of identifying anonymous classes.
@timtebeek 
- no new files were added

fix: skip finalizing anonymous class fields in FinalizeLocalVariables

---

src/main/java/org/openrewrite/staticanalysis/IsEmptyCallOnCollections.java
src/test/java/org/openrewrite/staticanalysis/IsEmptyCallOnCollectionsTest.java

Not only size comparisons with zero can be optimized to isEmpty() calls. Additionally we can do (plus order changes):
* size() < 1 to isEmpty()
* size() >= 1 to !isEmpty()
real life code
I've changed one of the existing unit tests. It was obviously meant to test `size() == 0` and `0 == size()` (to create all 8 variants of positive and negative tests).

Transform collection.size() < 1 to isEmpty()

---

src/main/java/org/openrewrite/staticanalysis/ModifierOrder.java
src/test/java/org/openrewrite/staticanalysis/ModifierOrderTest.java

Added specific unit test for linked issue and implement custom comparator to avoid the issue
Closes #187 
This fix should be implemented through `J.Modifier.Type::ordinal` modifying `default` element position in enum to be placed at fifth position.

Fix `default` modifier type position to comply with Java Language Specification

---

src/main/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateFields.java
src/test/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateFieldsTest.java

Removing comments attached to next statement (or end of enclosing class) when removing a variable declarations, that "belongs" to our statement because it has no new line between the statement and the comment.
When removing unused private fields, the comment seems to get "attached" to the previous statement.
Closes https://github.com/moderneinc/support-app/issues/15
Corner cases not taken into consideration where we should not remove the comment
@knutwannheden @timtebeek 
Maybe getting the next statement with cursors instead of storing it in a structure when traversing the list

remove comments from same line

---

src/main/java/org/openrewrite/staticanalysis/RemoveEmptyJavaDocParameters.java
src/test/java/org/openrewrite/staticanalysis/RemoveEmptyJavaDocParametersTest.java

There was a lot of missing scenarios on the tests that were causing bugs (wrong format of last lines, first lines, even index out of bounds on some very rare scenarios).
Added all the missing combinations of [param, return, throws], [regular, singleLine, firstLine], [withSpace, noSpace].
Fixed the bugs not originally covered with the new tests.
Fixes https://github.com/moderneinc/support-app/issues/14 and hopefully all other bugs in this recipe.
@timtebeek @knutwannheden

RemoveEmptyJavaDocParameters: added tests + fixed bugs

---

src/main/java/org/openrewrite/staticanalysis/UseDiamondOperator.java
src/test/java/org/openrewrite/staticanalysis/UseDiamondOperatorTest.java

We are trying to detect when we are calling a generic method with type inference, so we do not apply the diamond operator in those scenarios, as we cannot guarantee that the type inference will still work after applying the diamond operator.
Fixes https://github.com/moderneinc/support-app/issues/11
We've found some examples where we are producing invalid code due to applying the diamond operator when calling a generic method, thus breaking the type inference. 
@timtebeek @knutwannheden @jkschneider @kunli2 
I was trying to detect the type inference by trying to find the method in the declaring class, since the methodType I have from the invocation has the types resolves to the inferred ones. But with the TypeUtils.findDeclaredMethod I could not find it, because it's trying to match the …

no diamond when argument to generic method

---

src/main/java/org/openrewrite/staticanalysis/RenameLocalVariablesToCamelCase.java
src/test/java/org/openrewrite/staticanalysis/RenameLocalVariablesToCamelCaseTest.java

Removed the exception on `final` modifier.
According to https://rules.sonarsource.com/java/RSPEC-117/ there is no such exception on `final` modifier. Maybe this comes from the C variant https://rules.sonarsource.com/c/RSPEC-117/ where it mentions that `const` vars are excluded.
Fixes https://github.com/moderneinc/support-app/issues/9
@pstreef @timtebeek @kunli2 @traceyyoshima

rename final variables too

---

src/main/java/org/openrewrite/staticanalysis/ChainStringBuilderAppendCalls.java
src/main/java/org/openrewrite/staticanalysis/FinalizePrivateFields.java
src/main/java/org/openrewrite/staticanalysis/HiddenFieldVisitor.java
src/main/java/org/openrewrite/staticanalysis/NoDoubleBraceInitialization.java
src/main/java/org/openrewrite/staticanalysis/RemoveEmptyJavaDocParameters.java
src/main/java/org/openrewrite/staticanalysis/RemoveExtraSemicolons.java
src/main/java/org/openrewrite/staticanalysis/RemoveUnneededBlock.java
src/main/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariables.java
src/main/java/org/openrewrite/staticanalysis/ReplaceDuplicateStringLiterals.java
src/main/java/org/openrewrite/staticanalysis/ReplaceOptionalIsPresentWithIfPresent.java
src/main/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterface.java

Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.ReplaceLambdaWithMethodReference?organizationId=T3BlblJld3JpdGU%3D

Use method references in lambdas

---

src/main/java/org/openrewrite/staticanalysis/JavaElementFactory.java
src/main/java/org/openrewrite/staticanalysis/MinimumSwitchCases.java
src/test/java/org/openrewrite/staticanalysis/MinimumSwitchCasesTest.java

When the types are not known in advance the `JavaTemplate` classpath can also not be configured for these types. As a consequence the corresponding elements cannot be properly type-attributed.
So that the result of `MinimumSwitchCases` is properly type-attributed when transforming a `switch` over an enum, the recipe now manually creates the LST. Then the `ShortenFullyQualifiedTypeReferences` visitor also works properly.

Manually create LST for enums in `MinimumSwitchCases`

---

src/main/java/org/openrewrite/staticanalysis/RemoveUnreachableCodeVisitor.java
src/main/java/org/openrewrite/staticanalysis/SimplifyConstantIfBranchExecution.java
src/test/java/org/openrewrite/staticanalysis/SimplifyConstantIfBranchExecutionTest.java

This PR improves the `SimplifyConstantIfBranchExecution` recipe to simplify `if`s even if they have jumps (`return`, `throw`, `break`, or `continue`) in the branch we keep. The recipe will now also remove any unreachable code introduced by simplifying these `if`s.
I added numerous unit tests to demonstrate the new behavior.
Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/192
I considered implementing the unreachable code elimination as another recipe. However, it feels like it's tightly coupled to the `if` simplification itself; unreachable code is a compile-time error, so if this recipe is going to simplify these `if`s, I think it should do so cleanly.

Simplify `if`s with literal conditions even if they jump

---

src/main/java/org/openrewrite/staticanalysis/RenameLocalVariablesToCamelCase.java
src/test/java/org/openrewrite/staticanalysis/RenameLocalVariablesToCamelCaseTest.java

Many frameworks depend on method argument names to use for request parameter names or json field names. By renaming these without knowing how the frameworks use these we can make breaking changes. It's better to do no change.
Non camel case names are kept in method argument names.
Do no harm
`isMethodArgument()`
@joanvr @timtebeek 
no

RenameLocalVariablesToCamelCase: Do not rename method argument names.

---

src/main/java/org/openrewrite/staticanalysis/FallThroughVisitor.java
src/test/java/org/openrewrite/staticanalysis/FallThroughTest.java

A `break` must only be added if a case body terminates normally.

`FallThrough` must only add `break` on normal termination

---

src/main/java/org/openrewrite/staticanalysis/RemoveRedundantTypeCast.java
src/test/java/org/openrewrite/staticanalysis/RemoveRedundantTypeCastTest.java

The `RemoveRedundantTypeCast` recipe will now also remove casts when the types involve generics. Further, when the type cast is the expression of a `return` statement, then the target type will be derived from the corresponding method declaration if any (lambdas are not supported here yet).
Note: This implementation relies on openrewrite/rewrite#3655.

Allow `RemoveRedundantTypeCast` to deal with generics

---

src/main/java/org/openrewrite/staticanalysis/RemoveRedundantTypeCast.java
src/main/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterface.java
src/test/java/org/openrewrite/staticanalysis/RemoveRedundantTypeCastTest.java
src/test/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterfaceTest.java

We need to cast the lambda expression, when we have some unbounded generics on it's body. Right now I'm trying to identify those by searching for method invocations of methods with arguments with parametrized types with generics, but this just narrows it a bit, but those generics not necessarily are unbounded without the explicit cast. 
Also, changed the `methodArgumentRequiresCast` and previous check to accept MethodCall instead of `J.MethodInvocation`, so we can also reuse it for `J.NewClass` too
Fixes https://github.com/moderneinc/support-app/issues/17
How we can detect better when it's needed to add the cast and when it's redundant?

Cast when needed on lambda expressions

---

src/main/java/org/openrewrite/staticanalysis/FinalizePrivateFields.java
src/test/java/org/openrewrite/staticanalysis/FinalizePrivateFieldsTest.java

When a static field is assigned in a constructor, count that as assigned multiple times.
Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/177

Do not finalize private static fields assigned in constructor

---

src/main/java/org/openrewrite/staticanalysis/ExplicitLambdaArgumentTypes.java
src/main/java/org/openrewrite/staticanalysis/ReferentialEqualityToObjectEquals.java
src/main/java/org/openrewrite/staticanalysis/StringLiteralEquality.java
src/test/java/org/openrewrite/staticanalysis/ReferentialEqualityToObjectEqualsTest.java

These are various quick fixes identified by https://github.com/openrewrite/rewrite/pull/3743.
The changes set the JavaTypes to the same types the compiler creates for the same code.
Changes:
- The JavaType will be set correctly after changes in ExplicitLambdaArgumentTypes, ReferentialEqualityToObjectEquals, and StringLiteralEquality.

Set types based on the java compiler.

---

src/main/java/org/openrewrite/staticanalysis/LambdaBlockToExpression.java
src/test/java/org/openrewrite/staticanalysis/LambdaBlockToExpressionTest.java
src/test/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterfaceTest.java

This PR will enable the transformation of lambdas with method invocation as body.
Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/236
1. The first test case I added doesn't work, see comment in code
2. I had to explicitly set the whitespace in the return statement (LambdaBlockToExpression.java L61) in order to have the code move up to the previous line. Is there a cleaner way to do that?

feature(LambdaBlockToExpression): convert lambda with method invocation as well

---

src/main/java/org/openrewrite/staticanalysis/NeedBraces.java
src/test/java/org/openrewrite/staticanalysis/NeedBracesTest.java

When there is a trailing comment on the line of the nested statement which gets wrapped with braces, then the braces should remain a trailing comment for that statement.
So the code:
```java
if (foo)
return true; // early return
```
should be transformed into:
```java
if (foo) {
return true; // early return
}
```

`NeedBraces`: Deal with trailing comments

---

src/main/java/org/openrewrite/staticanalysis/BigDecimalDoubleConstructor.java
src/main/resources/META-INF/rewrite/common-static-analysis.yml
src/test/java/org/openrewrite/staticanalysis/BigDecimalDoubleConstructorTest.java

Simple recipe for fixing the double constructor.
Signed-off-by: Jonathan Leitschuh <Jonathan.Leitschuh@gmail.com>
Added a recipe to detect and fix using the improper `new BigDecimal(double)` constructor
More fun times with refaster annotations!
Is it fine I added this to `CommonStaticAnalysis`?

Add BigDecimalDoubleConstructor Recipe

---

src/main/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReference.java
src/test/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReferenceTest.java

Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/237

ReplaceLambdaWithMethodReference skip parameterized method return types

---

src/main/java/org/openrewrite/staticanalysis/FixStringFormatExpressions.java
src/test/java/org/openrewrite/staticanalysis/FixStringFormatExpressionsTest.java

Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/260
- https://github.com/openrewrite/rewrite-static-analysis/issues/260

Do not escape newline in FixStringFormatExpressions

---

src/main/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReference.java

Use this link to re-run the recipe: https://app.moderne.io/recipes/tech.picnic.errorprone.refasterrules.StringRulesRecipes?organizationId=T3BlblJld3JpdGU%3D

refactor: Refaster rules related to expressions dealing with `String`s

---

src/main/java/org/openrewrite/staticanalysis/RenamePrivateFieldsToCamelCase.java
src/test/java/org/openrewrite/staticanalysis/RenamePrivateFieldsToCamelCaseTest.java

Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/267
Mirrors what we do in `RemoveUnusedPrivateFields`
https://github.com/openrewrite/rewrite-static-analysis/blob/106421ad4d1db3fe062c8743d042627e07598a8c/src/main/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateFields.java#L42
@blipper

Skip RenamePrivateFieldsToCamelCase when using lombok

---

src/main/java/org/openrewrite/staticanalysis/SimplifyConstantIfBranchExecution.java
src/test/java/org/openrewrite/staticanalysis/SimplifyConstantIfBranchExecutionTest.java

Recognize when the recipe cannot optimize to a constant condition and return the if-condition as before all attempted optimizations.
Fixes #286.

Avoid parenthesis only cleanup in SimplifyConstantIfBranchExecution

---

src/main/java/org/openrewrite/staticanalysis/InstanceOfPatternMatch.java
src/test/java/org/openrewrite/staticanalysis/InstanceOfPatternMatchTest.java

Fix bug in InstanceOfPatternMatch getting the variable name from the name of a nested class.
Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/290
@timtebeek

Fix bug in InstanceOfPatternMatch getting the variable name from the name of a nested class

---

src/main/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateMethods.java
src/test/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateMethodsTest.java

`RemoveUnusedPrivateMethods` should ignore class annotated with `@SupressWarning("unused")`

---

src/main/java/org/openrewrite/staticanalysis/InstanceOfPatternMatch.java
src/test/java/org/openrewrite/staticanalysis/InstanceOfPatternMatchTest.java

Unit test and a possible straight-forward fix for
- #297

InstanceOfPatternMatch: Generic type without parameters

---

src/main/java/org/openrewrite/staticanalysis/RemoveEmptyJavaDocParameters.java
src/main/java/org/openrewrite/staticanalysis/RemoveJavaDocAuthorTag.java
src/test/java/org/openrewrite/staticanalysis/RemoveEmptyJavaDocParametersTest.java
src/test/java/org/openrewrite/staticanalysis/RemoveJavaDocAuthorTagTest.java

- Fixes #119 
- Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/98

Remove empty lines after rewrite

---

src/main/java/org/openrewrite/staticanalysis/UseStringReplace.java
src/test/java/org/openrewrite/staticanalysis/UseStringReplaceTest.java

If the replacement string of String.replaceAll contains $ or \, we should not rewrite it as these indicate special replacements: https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/util/regex/Matcher.html#replaceAll(java.lang.String)
- Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/301

Do not rewrite String.replaceAll with special chars in replacement string

---

src/main/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterface.java
src/test/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterfaceTest.java

For a method that has a type parameter, we can't replace anonymous class declarations with a lambda. For example:
```java
public interface I {
<T> List<T> call();
}
// Can't be replaced by lambda
final I i = new I() {
@Override
public <T> List<T> call() { ... }
};
```
The proposed fix is to check the method in question for type parameters, and if there are any, return early from `UseLambdaForFunctionalInterface` without making any changes.
Fixes #309

Don't use lambdas for methods with type parameters.

---

src/main/java/org/openrewrite/staticanalysis/LambdaBlockToExpression.java
src/test/java/org/openrewrite/staticanalysis/LambdaBlockToExpressionTest.java

Also look at number of arguments when looking for methods that might conflict in LambdaBlockToExpression.
The compiler should not get confused in there are a differing number of arguments in same name methods.
Allow adoption into
- https://github.com/openrewrite/rewrite-testing-frameworks/pull/582

Convert additional lambdas to expressions based on number of args

---

src/main/java/org/openrewrite/staticanalysis/UseStringReplace.java
src/test/java/org/openrewrite/staticanalysis/UseStringReplaceTest.java

Make less cautious!
- Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/330

Fix overly cautious regexp for = UseStringReplace

---

src/main/java/org/openrewrite/staticanalysis/RemoveMethodCallVisitor.java
src/test/java/org/openrewrite/staticanalysis/RemoveMethodCallVisitorTest.java

`RemoveMethodCallVisitor` can now remove method invocations in a fluent chain, assuming that the select is also a method invocation and of the same return type. In particular, this works for the builder pattern.
- Fixes #339
Is partial support for this use-case worth the added complexity?
@timtebeek

Support fluent chains in RemoveMethodCallVisitor

---

src/main/java/org/openrewrite/staticanalysis/OperatorWrap.java
src/test/java/org/openrewrite/staticanalysis/OperatorWrapTest.java

Add WrapOption wrapOption to OperatorWrap, and change from a static visitor to an inline visitor. The actual code changes are a lot smaller when ignoring whitespace.
Projects often rely on detection, or the default which matches CheckStyle. Yet when you want to change or enforce a new standard, it's cumbersome to have to configure a style for every project when you just want to change what's used once, and henceforth rely on detected style again.
* Continue to ask folks to configure an explicit style.
* Accept the CheckStyle default of operators on next line.
* As discussed on https://github.com/openrewrite/rewrite/pull/4509#pullrequestreview-2319707088 we could also make it easier to provide one-off override of detected style, to prevent proliferation of one-off-override-flags. …

Add WrapOption to OperatorWrap to change detected style easily after running once

---

src/main/java/org/openrewrite/staticanalysis/AddSerialVersionUidToSerializable.java
src/main/java/org/openrewrite/staticanalysis/AtomicPrimitiveEqualsUsesGet.java
src/main/java/org/openrewrite/staticanalysis/ChainStringBuilderAppendCalls.java
src/main/java/org/openrewrite/staticanalysis/EmptyBlockVisitor.java
src/main/java/org/openrewrite/staticanalysis/ExplicitInitializationVisitor.java
src/main/java/org/openrewrite/staticanalysis/ExternalizableHasNoArgsConstructor.java
src/main/java/org/openrewrite/staticanalysis/FinalClassVisitor.java
src/main/java/org/openrewrite/staticanalysis/FinalizeMethodArguments.java
src/main/java/org/openrewrite/staticanalysis/FinalizePrivateFields.java
src/main/java/org/openrewrite/staticanalysis/HideUtilityClassConstructorVisitor.java
src/main/java/org/openrewrite/staticanalysis/InstanceOfPatternMatch.java
src/main/java/org/openrewrite/staticanalysis/IsEmptyCallOnCollections.java
src/main/java/org/openrewrite/staticanalysis/MinimumSwitchCases.java
src/main/java/org/openrewrite/staticanalysis/MissingOverrideAnnotation.java
src/main/java/org/openrewrite/staticanalysis/NoDoubleBraceInitialization.java
src/main/java/org/openrewrite/staticanalysis/ReferentialEqualityToObjectEquals.java
src/main/java/org/openrewrite/staticanalysis/RemoveCallsToObjectFinalize.java
src/main/java/org/openrewrite/staticanalysis/ReplaceValidateNotNullHavingVarargsWithObjectsRequireNonNull.java
src/main/java/org/openrewrite/staticanalysis/SimplifyBooleanReturn.java
src/main/java/org/openrewrite/staticanalysis/SortedSetStreamToLinkedHashSet.java
src/main/java/org/openrewrite/staticanalysis/TernaryOperatorsShouldNotBeNested.java
src/main/java/org/openrewrite/staticanalysis/UnnecessaryPrimitiveAnnotations.java
src/main/java/org/openrewrite/staticanalysis/UnnecessaryThrows.java
src/main/java/org/openrewrite/staticanalysis/UpperCaseLiteralSuffixes.java
src/main/java/org/openrewrite/staticanalysis/UseCollectionInterfaces.java
src/main/java/org/openrewrite/staticanalysis/UseForEachRemoveInsteadOfSetRemoveAll.java
src/main/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterface.java

Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.OperatorWrap?organizationId=T3BlblJld3JpdGU%3D#defaults=W3sidmFsdWUiOiJFT0wiLCJuYW1lIjoid3JhcE9wdGlvbiJ9XQ==

refactor: Operator wrapping on end of line

---

src/main/java/org/openrewrite/staticanalysis/InstanceOfPatternMatch.java
src/test/java/org/openrewrite/staticanalysis/InstanceOfPatternMatchTest.java

If type casts to types with defined type parameters are used, i.e. `List<Object>`, `List<String>` it is difficult to determine if possible at all if `instanceof List list` or `instanceof List<?> list` isappropriate. Soem cases where type cast without type params is used and with it is impossible to determine. Therefore, I think it is best not to touch such `instanceof` <-> `type cats` patterns.

InstanceOf: no action if type casts with specific type params used

---

src/main/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrows.java
src/test/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrowsTest.java

The CatchClauseOnlyRethrows will now correctly handle multicatch blocks that use the short hand syntax `catch(Foo | Bar exception) {...}`.
In issue https://github.com/openrewrite/rewrite/issues/4235, a bug was demonstrated that caused a `catch` statement to be incorrectly removed as a wider exception is specified later on. I found that the reason for this behavior is the incorrect handling of `catch(Foo | Bar exception)` when checking for a wider exception type. The current code only performs a direct comparison between the parameter type of the current `catch` statement and that of the next one. This works fine if the statement is of the form `catch(Foo exception)`. However, in the case where the shorthand `catch(Foo | Bar exception)` is used, direct comparison of their parameter type no …

Fix: `CatchClauseOnlyRethrows` does not handle multi catch correctly

---

src/main/java/org/openrewrite/staticanalysis/ReplaceDuplicateStringLiterals.java
src/test/java/org/openrewrite/staticanalysis/ReplaceDuplicateStringLiteralsTest.java

We could generate some unreasonably long variable names. By default, we will cap variable names at 100 characters but people can change this was desired.
We will crop the generated variable name to the nearest "_" if there is one available

Cap the lengths of generate names in the ReplaceDuplicateStringLiterals recipe

---

src/main/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrows.java
src/test/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrowsTest.java

This pull request includes changes to the `CatchClauseOnlyRethrows` class and its corresponding test class to improve the handling of multi-catch blocks and simplify the code.
* [`src/main/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrows.java`](diffhunk://#diff-ec75c4b7b267bbb601fc5ec16f9ac13b68208977fb41bb14c51e0ae5d6ad719bL113-L117): Removed type checks for the caught exception and its type, simplifying the `onlyRethrows` method, and allowing multi catch statement to be correctly handeled.
* [`src/test/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrowsTest.java`](diffhunk://#diff-09165a4b9dca9fbdf3d3e09ce293a6a3ceb8f699c25dd57dece3b667bec81789R144-R182): Added a new test case `tryCanBeRemovedWithMultiCatch` to ensure that try-catch blocks with multi catch exceptions …

Fix `CatchCauseOnlyRethrows` onlyRethrows check for multi catch statements

---

src/main/java/org/openrewrite/staticanalysis/ReplaceDuplicateStringLiterals.java
src/test/java/org/openrewrite/staticanalysis/ReplaceDuplicateStringLiteralsTest.java

Removing the configuration option to modify the maximum variable length and changing it from 100 to 40.
40 is already a very long variable name, and we don't think that people will be changing this max length

Setting the maximum generated variable length to 40

---

src/main/java/org/openrewrite/staticanalysis/ReplaceDuplicateStringLiterals.java
src/test/java/org/openrewrite/staticanalysis/ReplaceDuplicateStringLiteralsTest.java

VariableNameUtils already provides a list of used names in the scope :). We need to handle some edges slightly different
1: When the constant already exists, in this case by default this existing constant name wouldn't be used because it's already being used. In this case, we need to allow the recipe to use this variable 
2: We want to prevent namespace shadowing on existing constants (preventNamespaceShadowingOnExistingConstant is the associated test). When we solve edge 1, by allowing existing constants to be used, we break this edge case. As such we need to validate that we are assigning a name to the value which makes sense.

Updating ReplaceDuplicateStringLiterals recipe to use VariableNameUtils to track variable names

---

src/main/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariables.java
src/test/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariablesTest.java

- For https://github.com/openrewrite/rewrite-feature-flags/pull/35

Allow removal of unused local variables with side effects in initializer

---

src/main/java/org/openrewrite/staticanalysis/java/MoveFieldAnnotationToType.java
src/test/java/org/openrewrite/staticanalysis/java/MoveFieldAnnotationToTypeTest.java

The previous behaviour, move the fully qualified name which won't compile
The previous behaviour
`public void someFunction(@org.openrewrite.internal.lang.Nullable org.openrewrite.internal.MetricsHelper metrics)` -->
`public void someFunction(org.openrewrite.internal.@org.openrewrite.internal.lang.Nullable MetricsHelper metrics)`
New behaviour
`public void someFunction(@org.openrewrite.internal.lang.Nullable org.openrewrite.internal.MetricsHelper metrics)` -->
`public void someFunction(org.openrewrite.internal.@Nullable MetricsHelper metrics)`
related issue 
- https://github.com/moderneinc/ops/issues/477

Updating MoveFieldAnnotationToType to handle moving annotation which are fully defined

---

src/main/java/org/openrewrite/staticanalysis/AnnotateNullableMethods.java
src/test/java/org/openrewrite/staticanalysis/AnnotateNullableMethodsTest.java

The PR implements the recipe outlined in https://github.com/openrewrite/rewrite-static-analysis/issues/328. The new recipe will automatically add a `@org.jspecify.annotation.Nullable` to _non-private_ methods that may return null. It does so by scanning methods and checking their return statements for potential null values. Apart from the literal `return null` it will also take methods on collection which are know to be null (based on : [error-prone](https://github.com/google/error-prone/blob/5ada179028452868623a1aa8f11eee2996886454/core/src/main/java/com/google/errorprone/bugpatterns/nullness/ReturnMissingNullable.java#L127-L191l)), such as `Map.get`, `Map.put`, `Queue.poll`..etc. Null that are the result of `lambda`, or streams, are currently ignored.
To quote this issue …

Add `AnnotateNullableMethods` recipe

---

src/main/java/org/openrewrite/staticanalysis/UnnecessaryReturnAsLastStatement.java
src/main/resources/META-INF/rewrite/common-static-analysis.yml
src/test/java/org/openrewrite/staticanalysis/UnnecessaryReturnAsLastStatementTest.java

Adding a new recipe to remove `return` if it's the last statement of a `void` method.
- Closes #75

Unnecessary `return` as last statement in `void` method

---

src/main/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrows.java
src/test/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrowsTest.java
src/test/java/org/openrewrite/staticanalysis/JavaToCsharp.java

Take into account a possible `J.Empty` expression for a throws statement
@OlegDokuka @knutwannheden @timtebeek 
In C# an implicit throw like this
```
catch (Exception ex)
{
throw;
}
```
is valid code and it's mapped to a `J.Empty` expression

Adjust `CatchClauseOnlyRethrows` to work with C#

---

src/main/java/org/openrewrite/staticanalysis/AtomicPrimitiveEqualsUsesGet.java
src/main/java/org/openrewrite/staticanalysis/CaseInsensitiveComparisonsDoNotChangeCase.java
src/main/java/org/openrewrite/staticanalysis/CovariantEquals.java
src/main/java/org/openrewrite/staticanalysis/EqualsAvoidsNull.java
src/main/java/org/openrewrite/staticanalysis/ExternalizableHasNoArgsConstructor.java
src/main/java/org/openrewrite/staticanalysis/FixStringFormatExpressions.java
src/main/java/org/openrewrite/staticanalysis/IndexOfChecksShouldUseAStartPosition.java
src/main/java/org/openrewrite/staticanalysis/IndexOfReplaceableByContains.java
src/main/java/org/openrewrite/staticanalysis/IndexOfShouldNotCompareGreaterThanZero.java
src/main/java/org/openrewrite/staticanalysis/NestedEnumsAreNotStatic.java
src/main/java/org/openrewrite/staticanalysis/NewStringBuilderBufferWithCharArgument.java
src/main/java/org/openrewrite/staticanalysis/NoFinalizer.java
src/main/java/org/openrewrite/staticanalysis/NoValueOfOnStringType.java
src/main/java/org/openrewrite/staticanalysis/ObjectFinalizeCallsSuper.java
src/main/java/org/openrewrite/staticanalysis/PrimitiveWrapperClassConstructorToValueOf.java
src/main/java/org/openrewrite/staticanalysis/RenameLocalVariablesToCamelCase.java
src/main/java/org/openrewrite/staticanalysis/RenamePrivateFieldsToCamelCase.java
src/main/java/org/openrewrite/staticanalysis/ReplaceStringBuilderWithString.java
src/main/java/org/openrewrite/staticanalysis/StringLiteralEquality.java
src/main/java/org/openrewrite/staticanalysis/UseJavaStyleArrayDeclarations.java
src/main/java/org/openrewrite/staticanalysis/WriteOctalValuesAsDecimal.java
src/main/java/org/openrewrite/staticanalysis/csharp/CSharpFileChecker.java

Excluded CSharp for some recipes + made some recipes a little bit more modern
Some recipes don't work for C#.

Improve recipes and excluded them from C# codebase if needed

---

src/main/java/org/openrewrite/staticanalysis/EqualsAvoidsNull.java
src/main/java/org/openrewrite/staticanalysis/EqualsAvoidsNullVisitor.java
src/test/java/org/openrewrite/staticanalysis/EqualsAvoidsNullTest.java

Hi,
I might have found an issue in my local project where around 90 violations flagged by PMD are not being replaced correctly. Some of these violations seem related to a list and method arguments.
Could you please take over and enable the necessary tests to confirm if this is indeed an issue?
Thanks in advance!  
@timtebeek 
@knutwannheden 
@ggerbaud

`EqualsAvoidsNull` should flip arguments for constants

---

src/main/java/org/openrewrite/staticanalysis/ExplicitInitializationVisitor.java
src/test/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrowsTest.java
src/test/java/org/openrewrite/staticanalysis/ExplicitInitializationTest.java
src/test/java/org/openrewrite/staticanalysis/charp/ExplicitInitializationVisitorCsharpTest.java
src/test/java/org/openrewrite/staticanalysis/charp/JavaToCsharp.java

Nothing, it just adds a test to prove C# works with the ExplicitInitialization recipe.

Prove C# support for ExplicitInitialization recipe

---

src/test/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrowsTest.java
src/test/java/org/openrewrite/staticanalysis/charp/CatchClauseOnlyRethrowsCsharpTest.java

As we defined a csharp package in the test folder, let's move the `verifyCsharpImplicitThrow` in the right place.
Code consistency.

Move `verifyCsharpImplicitThrow` to own Csharp test class

---

src/main/java/org/openrewrite/staticanalysis/CovariantEquals.java
src/main/java/org/openrewrite/staticanalysis/EmptyBlockVisitor.java
src/main/java/org/openrewrite/staticanalysis/ExplicitInitializationVisitor.java
src/main/java/org/openrewrite/staticanalysis/FinalizeMethodArguments.java
src/main/java/org/openrewrite/staticanalysis/HiddenFieldVisitor.java
src/main/java/org/openrewrite/staticanalysis/HideUtilityClassConstructorVisitor.java
src/main/java/org/openrewrite/staticanalysis/NoRedundantJumpStatements.java
src/main/java/org/openrewrite/staticanalysis/OperatorWrap.java
src/main/java/org/openrewrite/staticanalysis/RenameMethodsNamedHashcodeEqualOrToString.java
src/main/java/org/openrewrite/staticanalysis/ReplaceDuplicateStringLiterals.java
src/main/java/org/openrewrite/staticanalysis/TernaryOperatorsShouldNotBeNested.java
src/main/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterface.java

Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.CompareEnumsWithEqualityOperator?organizationId=T3BlblJld3JpdGU%3D

refactor: Enum values should be compared with "=="

---

src/main/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterface.java
src/test/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterfaceTest.java

No more lambda conversion for `UseLambdaForFunctionalInterface` recipe when the anonymous class is within a constructor of a Enum class and uses a static field of this very class.
- https://github.com/openrewrite/rewrite-static-analysis/issues/413

`UseLambdaForFunctionalInterface` recipe should not convert when code uses a static field from enum constructor

---

src/main/java/org/openrewrite/staticanalysis/EqualsAvoidsNullVisitor.java
src/test/java/org/openrewrite/staticanalysis/EqualsAvoidsNullTest.java

- Fixes #434, but makes another test fail.
Avoid unconditionally removing the whitespace prefix of the optimized expression.
It depends on the parent, whether removing whitespace is syntactially valid.
This is incomplete, as another test fails now. We get `if( "test".equals(s)) {}` (note the unwanted space after the opening brace) in another test case, which comes from optimizing `if(s != null && s.equals("test"))` and still using the space character which was after the `&&` operator.
I'm not sure about the correct way to proceed. When I worked with domain specific languages in another project, the formatter of the language (used in the serializer) would enforce additional whitespace in a case like this ("return", ADDITIONAL_SPACE_INSERTED_HERE, returnValue) when processing the return …

Don't remove necessary whitespace in EqualsAvoidNull

---

src/test/java/org/openrewrite/staticanalysis/SimplifyBooleanExpressionTest.java

The test wasn't implemented according to its intention. The intended double negation was completely missing.
Someone might want to check if this was optimized away at some point in the past by applying the rewrite recipes to its own code. If so, other places (in test code) might be affected by wrongly having been refactored.

Restore double negation test in `SimplifyBooleanExpressionTest`

---

src/main/java/org/openrewrite/staticanalysis/UnnecessaryThrows.java
src/test/java/org/openrewrite/staticanalysis/UnnecessaryThrowsTest.java

This adds a test for issue #443

Skip constructors in `UnnecessaryThrows` for now

---

src/main/java/org/openrewrite/staticanalysis/UnnecessaryCatch.java
src/test/java/org/openrewrite/staticanalysis/UnnecessaryCatchTest.java

Similar to `catch (Exception e)` it is undesired to remove `catch (Throwable t)` blocks as it changes the runtime behavior.
The UnnecessaryCatch rule did always remove `catch (Throwable t)`, which changes runtime behavior.
Although the use of Throwable isn't recommended there are use cases. When `catch (Throwable t)` is removed it changes the runtime behavior.

feat: prevent UnnecessaryCatch from removing `catch (Throwable t)`

---

src/main/java/org/openrewrite/staticanalysis/UnnecessaryCatch.java
src/test/java/org/openrewrite/staticanalysis/UnnecessaryCatchTest.java

Constructors weren't considered when the list of thrown exceptions was determined.
Constructors can also declare exceptions, they should be considered before removing unnecessary catch blocks.
@timtebeek 
I did not find any documentation about applying the code formatter and could not find a gradle task.

fix: consider constructors in UnnecessaryCatch

---

gradle/wrapper/gradle-wrapper.properties
src/main/java/org/openrewrite/staticanalysis/RemoveExtraSemicolons.java
src/test/java/org/openrewrite/staticanalysis/AbstractClassPublicConstructorTest.java
src/test/java/org/openrewrite/staticanalysis/RemoveExtraSemicolonsTest.java

Description was misleading and don't describe all changes.
Better understandability for recipes purpose.

Expand `RemoveExtraSemicolons` description

---

src/main/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrows.java
src/main/java/org/openrewrite/staticanalysis/NoEqualityInForCondition.java
src/test/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrowsTest.java

The recipe `CatchClauseOnlyRethrows` supports multiple exception types now completely.
Code like
```java
try {
// something
} catch (SomeException | SomeOtherException e) {
throw e;
} catch (Exception e) {
throw new WhateverException(e);
}
```
will currently be altered by the recipe, which is incorrect.

Improve CatchClauseOnlyRethrows to support MultiCatch completely

---

build.gradle.kts
src/main/java/org/openrewrite/staticanalysis/CombineSemanticallyEqualCatchBlocks.java
src/main/java/org/openrewrite/staticanalysis/DefaultComesLastVisitor.java
src/main/java/org/openrewrite/staticanalysis/MinimumSwitchCases.java
src/test/java/org/openrewrite/staticanalysis/DefaultComesLastTest.java
src/test/java/org/openrewrite/staticanalysis/EqualsAvoidsNullTest.java

- Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/461
Fails for now with what likely needs an upstream fix first:
```
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.openrewrite.java.tree.J$Identifier.getSimpleName()" is null
at org.openrewrite.java.JavaPrinter.visitCase(JavaPrinter.java:488)
at org.openrewrite.java.JavaPrinter.visitCase(JavaPrinter.java:35)
at org.openrewrite.java.tree.J$Case.acceptJava(J.java:1118)
at org.openrewrite.java.tree.J.accept(J.java:58)
at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
... 57 more
```

DefaultComesLast should work on Java 21 Object switch

---

src/test/java/org/openrewrite/staticanalysis/RemoveExtraSemicolonsTest.java

Adding a single test case for `RemoveExtraSemicolons` recipe test.
This requires https://github.com/openrewrite/rewrite/pull/5147 to work.
- fixing https://github.com/openrewrite/rewrite/issues/5146

Adding test case to `RemoveExtraSemicolons` for enum with no values

---

src/main/java/org/openrewrite/staticanalysis/PrimitiveWrapperClassConstructorToValueOf.java
src/test/java/org/openrewrite/staticanalysis/PrimitiveWrapperClassConstructorToValueOfTest.java

Conversion of Float(double) constructor handles primitive double use case.  Float.valueOf(double) does not exist.
- Fixes #476 
Fix took the simplest approach to conversion of double to float and used the Java Float.java constructors as the example.
Could not find any workarounds.

Fixed primitive wrapper for double to float conversion

---

src/main/java/org/openrewrite/staticanalysis/EmptyBlockVisitor.java
src/test/java/org/openrewrite/staticanalysis/EmptyBlockTest.java

Fixing `EmptyBlock` recipe not to corrupt the code.
- fixes #314

Fixing `EmptyBlock` recipe not to alter code for unsupported operators

---

src/main/java/org/openrewrite/staticanalysis/AnnotateNullableMethods.java
src/test/java/org/openrewrite/staticanalysis/AnnotateNullableMethodsTest.java

Added option to provide a custom FQN to AnnotateNullableMethods recipe
As requested in https://github.com/openrewrite/rewrite-static-analysis/issues/428
@jevanlingen 
@Laurens-W 
@greg-at-moderne

Added option to provide a custom FQN to AnnotateNullableMethods recipe

---

src/main/java/org/openrewrite/staticanalysis/EqualsAvoidsNull.java
src/test/java/org/openrewrite/staticanalysis/EqualsAvoidsNullTest.java

Increasing the idempotency of `EqualsAvoidsNull` recipe. Specifically preventing thrashing between expressions like `FOO.equals(BAR)` changed to `BAR.equals(FOO)` changed to `FOO.equals(BAR)`, etc.
The test code has been taken from #487 (kudos to @pankratz76).
- fixes additional problems reported in #472

Increased idempotency of EqualsAvoidsNull by avoiding too many swaps

---

build.gradle.kts

Exclude `dataflow-errorprone` over shaded vulnerable Guava

---

src/test/java/org/openrewrite/staticanalysis/CombineSemanticallyEqualCatchBlocksTest.java

Ignoring a single test case of `combineSameSemanticallyEquivalentMethodTypes` in `CombineSemanticallyEqualCatchBlocksTest`.
It started to fail after https://github.com/openrewrite/rewrite/pull/5286
and should be fixed in #506.

Ignoring combineSameSemanticallyEquivalentMethodTypes test case

---

src/main/java/org/openrewrite/staticanalysis/SimplifyBooleanReturn.java
src/test/java/org/openrewrite/staticanalysis/SimplifyBooleanReturnTest.java

When a `simplified boolean return` would result in `!(!aBool)`, `aBool` is returned.

Avoid double negation in SimplifyBooleanReturn

---

src/main/java/org/openrewrite/staticanalysis/ChainStringBuilderAppendCalls.java
src/main/java/org/openrewrite/staticanalysis/ReplaceStringBuilderWithString.java
src/test/java/org/openrewrite/staticanalysis/ReplaceStringBuilderWithStringTest.java

This retains comments that may appear such that the following scenario can be supported.
```
@Test
@Issue("https://github.com/openrewrite/rewrite-static-analysis/issues/88")
void retainComments() {
rewriteRun(
//language=java
java(
"""
class A {
void foo() {
String scenarioFour = new StringBuilder()
// A
.append("A")
// B
.append("B")
// C
.append("C")
.toString();
}
}
""",
"""
class A {
void foo() {
String scenarioFour =
// A
"A" +
// B
"B" +
// C
"C";
}
}
"""
)
);
}
```
- https://github.com/openrewrite/rewrite-static-analysis/pull/504#issuecomment-2802478931
-related to https://github.com/openrewrite/rewrite-static-analysis/issues/88

ReplaceStringBuilderWithString should keep comments

---

src/main/java/org/openrewrite/staticanalysis/FinalizeLocalVariables.java
src/test/java/org/openrewrite/staticanalysis/FinalizeLocalVariablesTest.java

- Added a check to the `FinalizeLocalVariables` recipe to ignore variables in the resources block of try-with-resources
- Added a test to validate variables inside try-catch-finally are still finalized
Fixes:
- https://github.com/openrewrite/rewrite-static-analysis/issues/359

Don't finalize try-with-resources vairables as they are implicitly final

---

src/main/java/org/openrewrite/staticanalysis/UseCollectionInterfaces.java
src/test/java/org/openrewrite/staticanalysis/UseCollectionInterfacesTest.java

UseCollectionInterfaces now also visits methodInvocation to change their type. This causes the imports to be removed correctly.
Fixes:
- https://github.com/openrewrite/rewrite-static-analysis/issues/357

UseCollectionInterfaces updates methodInvovations type info to enable import removal

---

src/main/java/org/openrewrite/staticanalysis/ReplaceClassIsInstanceWithInstanceof.java
src/test/java/org/openrewrite/staticanalysis/ReplaceClassIsInstanceWithInstanceofTest.java

Fixing `ReplaceClassIsInstanceWithInstanceof` wrt to parenthesis being sometimes needed around the `instanceof`.
Fix the errors observed in real-life, e.g.
[this code in spring-hateoas](https://github.com/spring-projects/spring-hateoas/blob/f8850d3d15db48bf0ddac3ce12e8197c004e9c5d/src/main/java/org/springframework/hateoas/mediatype/collectionjson/Jackson2CollectionJsonModule.java#L921) throws:
```
Message:
class org.openrewrite.java.tree.J$Parentheses cannot be cast to class org.openrewrite.java.tree.J$InstanceOf (org.openrewrite.java.tree.J$Parentheses and org.openrewrite.java.tree.J$InstanceOf are in unnamed module of loader 'app')
Detail:
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Parentheses cannot be cast to class org.openrewrite.java.tree.J$InstanceOf …
```

Handling parentheses sometimes needed around instanceof

---

src/main/java/org/openrewrite/staticanalysis/ReplaceDeprecatedRuntimeExecMethods.java
src/test/java/org/openrewrite/staticanalysis/ReplaceDeprecatedRuntimeExecMethodsTest.java

Changing `ReplaceDeprecatedRuntimeExecMethods` not to visit references in Javadoc comments.
- fixes #526
Also I think we should add some `NoOpJavadocVisitor` in upstream rewrite to save the effort. Wdyt?

Exclude visiting Javadoc in ReplaceDeprecatedRuntimeExecMethods

---

src/main/java/org/openrewrite/staticanalysis/InstanceOfPatternMatch.java
src/test/java/org/openrewrite/staticanalysis/InstanceOfPatternMatchTest.java

We now only use the boxed variants of primitives when rewriting `instanceof`.
- fix #528

fix: use box for primitives when rewriting `instanceof` (#528)

---

src/main/java/org/openrewrite/staticanalysis/InstanceOfPatternMatch.java
src/test/java/org/openrewrite/staticanalysis/InstanceOfPatternMatchTest.java

In addition to the `cursor` scope, added the enclosing `J.If` scope for searching conflicting variable names.
- Fix https://github.com/openrewrite/rewrite-static-analysis/issues/334
- Fix https://github.com/openrewrite/rewrite-static-analysis/issues/481
- Fix https://github.com/openrewrite/rewrite/issues/2787
- It also can be a workaround for https://github.com/openrewrite/rewrite/issues/2776

Fix clashing variable names generated by `InstanceOfPatternMatch`

---

src/main/java/org/openrewrite/staticanalysis/AddSerialVersionUidToSerializable.java
src/test/java/org/openrewrite/staticanalysis/AddSerialAnnotationToSerialVersionUIDTest.java
src/test/java/org/openrewrite/staticanalysis/AddSerialVersionUidToSerializableTest.java
src/test/java/org/openrewrite/staticanalysis/HiddenFieldTest.java

To be able to choose from `1`, `1L`, or any other value.
Codebases often go for the `1L` value, so having an option to use that value is cool.
Unit test coverage, maybe?

Enable custom Serial Version UID

---

src/main/java/org/openrewrite/staticanalysis/UnnecessaryExplicitTypeArguments.java
src/test/java/org/openrewrite/staticanalysis/UnnecessaryExplicitTypeArgumentsTest.java

Adde rules to the removing unnecessary explicit type arguments recipe to deal with static method calls.
The recipe currently removes explicit type arguments from method calls that need it.

Handle static method calls when removing unnecessary explicit type arguments.

---

src/main/java/org/openrewrite/staticanalysis/RemoveUnneededBlock.java
src/test/java/org/openrewrite/staticanalysis/RemoveUnneededBlockTest.java
src/test/java/org/openrewrite/staticanalysis/SimplifyConstantIfBranchExecutionTest.java

- fixes #399 
Certain cases where there is an object assignment in an unneeded `if` block in the initial code can cause `SimplifyConstantIfBranchExecution` to leave scoping braces and unreachable lines in the code. The underlying cause is due to `RemoveUnneededBlock` deciding to not remove scoping braces if a block contains variable declarations, however, if the block also contains a return, then `SimplifyConstantIfBranchExecution` which also uses `RemoveUnreachableCodeVisitor` should be able to be unwrapped because there should be no conflicts after unreachable code is removed.
- Test example from submitted issue has been added.
- Deeper nested if examples included for `SimplifyConstantIfBranchExecution` tests and test example provided for `RemoveUnneededBlock` specifically covering …

SimplifyConstantIfBranchExecution leaves unreachable code

---

build.gradle.kts
src/main/java/org/openrewrite/staticanalysis/RemoveUnneededAssertion.java
src/test/java/org/openrewrite/staticanalysis/RemoveUnneededAssertionTest.java

- Finishes #166 
- Matching added for TestNG's `assertTrue(..)` and `assertFalse(..)` assertions so they too can be cleaned up when unneded

TestNG matching for RemoveUnneededAssertion

---

src/main/java/org/openrewrite/staticanalysis/UnnecessaryThrows.java
src/test/java/org/openrewrite/staticanalysis/UnnecessaryThrowsTest.java

- For https://github.com/apache/maven/pull/2291
- Needs https://github.com/openrewrite/rewrite/pull/5412

UnnecessaryThrows should not change API for protected methods

---

src/main/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariables.java
src/main/resources/META-INF/rewrite/examples.yml
src/test/java/org/openrewrite/staticanalysis/MinimumSwitchCasesTest.java
src/test/java/org/openrewrite/staticanalysis/RemoveUnusedLocalVariablesTest.java
src/test/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReferenceTest.java

This PR enhances the `RemoveUnusedLocalVariables` recipe in OpenRewrite by introducing a new configuration option: `onlyRemoveVariablesOfType`. This option allows users to specify a list of fully qualified class names; only unused local variables of those types will be considered for removal.
This change addresses an important scalability concern in large codebases. Removing **all** unused local variables often results in extensive, unrelated changes across a project, making code reviews cumbersome.

Enhance RemoveUnusedLocalVariables to support filtering by type

---

src/main/java/org/openrewrite/staticanalysis/MinimumSwitchCases.java
src/test/java/org/openrewrite/staticanalysis/MinimumSwitchCasesTest.java

`MinimumSwitchCases` ignores switches with cases with more than 1 break.
When a case contains several breaks rewriting it to an if-statement results in an if-statement with a break.

`MinimumSwitchCases` ignores switches with cases with more than 1 break.

---

src/main/java/org/openrewrite/staticanalysis/FallThroughVisitor.java
src/test/java/org/openrewrite/staticanalysis/FallThroughTest.java

- Added test
- Added check to find guaranteed returns
When there is a guaranteed return in a switch case, adding a `break;` will result in unreachable code.

Fallthrough should not add `break;` when statements contain a guaranteed return

---

src/main/java/org/openrewrite/staticanalysis/CustomImportOrder.java

Applying code suggestions in a single file.
Avoid noise in unrelated PRs, e.g.
```
src/main/java/org/openrewrite/staticanalysis/CustomImportOrder.java
lines 24-24
```

Applying code suggestions

---

src/main/java/org/openrewrite/staticanalysis/InstanceOfPatternMatch.java
src/test/java/org/openrewrite/staticanalysis/InstanceOfPatternMatchTest.java

When the cast type expression is a supertype of the instanceof type, the recipe should back off. The code semantics could change otherwise, because more instances can potentially pass the check. Fixes GH-572.
Type casts after `instanceof` checks which use a different type than the one used in the `instanceof` check itself will now be ignored since changing the `instanceof` type might alter the code semantics.
Issue #572
The `isCheckedCastCompatible` might be extended even further to take generic type variables into account. Cases like these could also be migrated, since the type variables are the same:
```java
// java 11
class A<T> {
void test(List<T> o) {
if (o instanceof ArrayList<?>) {
((ArrayList<T>) o).trimToSize();
}
}
}
// java 16+ where the reifiable type-restriction was lifted …
```

Do not pull Supertype-Cast to instanceof

---

src/main/java/org/openrewrite/staticanalysis/CustomImportOrder.java
src/test/java/org/openrewrite/staticanalysis/CustomImportOrderRecipeTest.java

Added regression test to verify that no default import order style is applied as a part of this issue:
- Closes https://github.com/openrewrite/rewrite-static-analysis/issues/574 
@timtebeek 
With this PR, we test the case where if no style is applied, the import order should not change.

Add regression test to verify that no default import order style is applied

---

src/main/java/org/openrewrite/staticanalysis/SimplifyBooleanExpressionWithDeMorgan.java
src/test/java/org/openrewrite/staticanalysis/SimplifyBooleanExpressionWithDeMorganTest.java

A new recipe called `SimplifyBooleanExpressionWithDeMorgan`.
Add a new recipe, the trigger was I wanted to use it in the after-visit in one of the other recipes (#656).
I was wondering whether to plug it into existing `SimplifyBooleanExpression` as it would fit the basic description. I could see pros and cons, but decided not to. Please share your thoughts on this.

Recipe to simplify Boolean expressions using De Morgan's laws

---

src/main/java/org/openrewrite/staticanalysis/SimplifyBooleanExpressionWithDeMorgan.java
src/test/java/org/openrewrite/staticanalysis/SimplifyBooleanExpressionWithDeMorganTest.java

Follow-up on #659. Adding a call to ParenthesizeVisitor on the changed node's parent.
Fixing a bug discovered when running the recipe against some OSS projects.
This is needed in some cases, especially when `&&` which is high precedence gets converted to `||` which has lower precedence.

SimplifyBooleanExpressionWithDeMorgan - Add parens when converting to OR

---

src/main/java/org/openrewrite/staticanalysis/UseDiamondOperator.java
src/test/java/org/openrewrite/staticanalysis/groovy/MinimumSwitchCasesTest.java

Applying code suggestions
To avoid noise in unrelated PRs:
```
src/main/java/org/openrewrite/staticanalysis/UseDiamondOperator.java
lines 276-277
lines 290-292
lines 309-309
src/test/java/org/openrewrite/staticanalysis/groovy/MinimumSwitchCasesTest.java
lines 19-19
```

Fixing code suggestions

---

src/main/java/org/openrewrite/staticanalysis/FinalizePrivateFields.java
src/test/java/org/openrewrite/staticanalysis/FinalizePrivateFieldsTest.java

Indentation is kept when running the `FinalizePrivateFields` recipe.
Prior to this PR, it would always create an indentation of 4 spaces prior to the modifiers.
You could argue this problem should actually be fixed in the `autoFormat` function. Though I do agree with that kind of thought, in this case it's still better to no use the auto formatting feature at all, as there are only two options:
- Newly added `final` modifier is the first modifier: no prefix
- Newly added `final` modifier is the not the first modifier: prefix.

Keep indentation when running `FinalizePrivateFields`

---

src/main/java/org/openrewrite/staticanalysis/PreferIncrementOperator.java
src/test/java/org/openrewrite/staticanalysis/PreferIncrementOperatorTest.java

Extensions of `PreferIncrementOperator` added in #676 to cover more cases - i.e. when the increment is not by `1`, but by some expression.
Cover more cases in the recipe.

PreferIncrementOperator - more coverage - compound assignment operators

---

src/test/java/org/openrewrite/staticanalysis/BooleanChecksNotInvertedTest.java
src/test/java/org/openrewrite/staticanalysis/SimplifyTernaryTest.java

Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.java.recipes.UseRewriteTestDefaults?organizationId=ODQ2MGExMTUtNDg0My00N2EwLTgzMGMtNGE1NGExMTBmZDkw

Refactor RewriteTest to use defaults method

---

src/main/java/org/openrewrite/staticanalysis/UseCollectionInterfaces.java
src/test/java/org/openrewrite/staticanalysis/UseCollectionInterfacesTest.java

Enhanced `UseCollectionInterfaces` recipe to prevent type conversions when concrete-class-specific methods are being used. 
Also, added support for  `java.util.Vector`
- Closes #688
- Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/671
- The `nonInterfaceMethods` to ensure we've covered all the important methods
- Two-phase approach, ie first detect and then transform. Whether this is the most efficient way

fix: Enhanced UseCollectionInterfaces to prevent conversions when non interface methods are used

---

src/main/java/org/openrewrite/staticanalysis/RemoveRedundantTypeCast.java
src/test/java/org/openrewrite/staticanalysis/RemoveRedundantTypeCastTest.java

- If a cast is performed with the **exact** same type as the expression, remove the cast.
- if a cast is performed on a methodCall and the type is a subtype of the expression, remove the cast.
- https://github.com/moderneinc/rewrite-hibernate/pull/28/files#r2266719230

Improve support method invocations for `RemoveRedundantTypeCast`

---

src/main/java/org/openrewrite/staticanalysis/NeedBraces.java
src/test/java/org/openrewrite/staticanalysis/NeedBracesTest.java

Support for-each loop in NeedBraces
