openrewrite/rewrite-static-analysis

- src/main/java/org/openrewrite/staticanalysis/UseAsBuilder.java
> added validation

- src/main/java/org/openrewrite/staticanalysis/RenameLocalVariablesToCamelCase.java
- src/main/java/org/openrewrite/staticanalysis/RenamePrivateFieldsToCamelCase.java
- src/test/java/org/openrewrite/staticanalysis/RenameLocalVariablesToCamelCaseTest.java
- src/test/java/org/openrewrite/staticanalysis/RenamePrivateFieldsToCamelCaseTest.java
fixes: https://github.com/openrewrite/rewrite-static-analysis/issues/103
Add test and proposed fix
> Rename(LocalVariables|PrivateFields)ToCamelCase do not replace _ if next character is not an alphabetic char

- src/main/java/org/openrewrite/staticanalysis/ReplaceOptionalIsPresentWithIfPresent.java
Sys out call corrupts spring boot language server comm to the client as it goes via sys in/out
> Remove sys out calls

- src/main/java/org/openrewrite/staticanalysis/ReplaceStackWithDeque.java
- Add DataFlowNodes for overridden methods
> Incorporate DataFlowNodes from rewrite-analysis

- src/main/java/org/openrewrite/staticanalysis/ReplaceStackWithDeque.java
- Add `DataFlowSpec` to replace `LocalFlowSpec`
> Add DataFlowSpec to ReplaceStackWithDeque

- src/main/java/org/openrewrite/staticanalysis/AddSerialVersionUidToSerializable.java
- src/main/java/org/openrewrite/staticanalysis/ExplicitLambdaArgumentTypes.java
- src/main/java/org/openrewrite/staticanalysis/FinalClassVisitor.java
- src/main/java/org/openrewrite/staticanalysis/FinalizeLocalVariables.java
- src/main/java/org/openrewrite/staticanalysis/FinalizeMethodArguments.java
- src/main/java/org/openrewrite/staticanalysis/FinalizePrivateFields.java
- src/main/java/org/openrewrite/staticanalysis/InstanceOfPatternMatch.java
- src/main/java/org/openrewrite/staticanalysis/JavaElementFactory.java
- src/main/java/org/openrewrite/staticanalysis/MinimumSwitchCases.java
- src/main/java/org/openrewrite/staticanalysis/NoPrimitiveWrappersForToStringOrCompareTo.java
- src/main/java/org/openrewrite/staticanalysis/ReferentialEqualityToObjectEquals.java
- src/main/java/org/openrewrite/staticanalysis/ReplaceDuplicateStringLiterals.java
- src/main/java/org/openrewrite/staticanalysis/SimplifyCompoundVisitor.java
- src/main/java/org/openrewrite/staticanalysis/SimplifyConsecutiveAssignments.java
- src/main/java/org/openrewrite/staticanalysis/SimplifyConstantIfBranchExecution.java
- src/main/java/org/openrewrite/staticanalysis/StringLiteralEquality.java
- src/main/java/org/openrewrite/staticanalysis/UseCollectionInterfaces.java
- src/main/java/org/openrewrite/staticanalysis/UseLambdaForFunctionalInterface.java
- src/main/resources/META-INF/rewrite/common-static-analysis.yml
- src/main/resources/META-INF/rewrite/static-analysis.yml
Use this link to re-run the recipe: http://localhost:3000/recipes/org.openrewrite.java.upgrade.MigrateToRewrite8?organizationId=T3BlblJld3JpdGU%3D
> refactor: Migrate rewrite from 7 to 8

- src/main/java/org/openrewrite/staticanalysis/SimplifyBooleanExpression.java
To reduce duplication. Depends on 
- https://github.com/openrewrite/rewrite/pull/3490
> Extend SimplifyBooleanExpressionVisitor

- src/test/java/org/openrewrite/staticanalysis/UnnecessaryExplicitTypeArgumentsTest.java
adding a failing test for https://github.com/openrewrite/rewrite-static-analysis/issues/164
> Unnecessary explicit type arguments removes necessary type arguments

- src/main/java/org/openrewrite/staticanalysis/RemoveUnreachableCodeVisitor.java
Using subList instead of helper method
> Refactor: Simplify RemoveUnreachableCodeVisitor

- src/main/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReference.java
- src/test/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReferenceTest.java
As shared instance might behave different from new instances
> No method reference on new class select

- src/main/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateFields.java
- src/test/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateFieldsTest.java
As discovered on
- https://github.com/openrewrite/rewrite-launchdarkly/pull/10
> RemoveUnusedPrivateFields should remove imports

- src/main/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateFields.java
- src/test/java/org/openrewrite/staticanalysis/RemoveUnusedPrivateFieldsTest.java
Adding a condition to skip applying the recipe if @lombok.Data annotation is found in the class
> #242 Fix remove unused private fields

- src/test/java/org/openrewrite/staticanalysis/BigDecimalDoubleConstructorTest.java
- src/test/java/org/openrewrite/staticanalysis/ReplaceOptionalIsPresentWithIfPresentTest.java
- src/test/java/org/openrewrite/staticanalysis/SimplifyTernaryTest.java
- src/test/java/org/openrewrite/staticanalysis/SortedSetStreamToLinkedHashSetTest.java
- src/test/java/org/openrewrite/staticanalysis/groovy/MinimumSwitchCasesTest.java
- src/test/java/org/openrewrite/staticanalysis/kotlin/RenameLocalVariablesToCamelCaseTest.java
- src/test/java/org/openrewrite/staticanalysis/kotlin/SimplifyBooleanExpressionTest.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.java.recipes.SelectRecipeExamples?organizationId=ZDI4ZjE4NTAtNTg0Yi00Zjk1LWFkZDgtOGQzY2ZiMzgwNmM4
> refactor: Automatically select recipe examples from the unit test cases of a recipe

- src/main/java/org/openrewrite/staticanalysis/ReplaceStringBuilderWithString.java
Remove deprecated code in place for new functionality.
https://github.com/openrewrite/rewrite/issues/3754#issuecomment-1850988722
Is not a complete implementation due to time constraints, will be able to complete any final changes as needed. Not tested with build.
@timtebeek
N/A
N/A
- [ No] I've added unit tests to cover both positive and negative cases
- [ No] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [No ] I've used the IntelliJ IDEA auto-formatter on affected files
> Fully remove part provider and last remaining references

- src/main/java/org/openrewrite/staticanalysis/UseAsBuilder.java
Fixes: https://github.com/openrewrite/rewrite-static-analysis/issues/263
> Clarify display name + desc for builder recipe

- src/main/java/org/openrewrite/staticanalysis/MethodNameCasing.java
To hopefully be clearer as to what it does. Based on feedback from the following issue: https://github.com/openrewrite/rewrite/issues/4180
> Adjusts MethdNameCasing name and description

- src/main/java/org/openrewrite/staticanalysis/MinimumSwitchCases.java
Disabled `MinimumSwitchCases` for C#
@timtebeek @OlegDokuka @macsux 
The reasoning for changing from switch to if-else is different for C# than for Java
> Disable `MinimumSwitchCases` for C#

- src/main/java/org/openrewrite/staticanalysis/EqualsAvoidsNullVisitor.java
- src/test/java/org/openrewrite/staticanalysis/EqualsAvoidsNullTest.java
merry xmass - this is the last one :-)
> Verify `EqualsAvoidsNullVisitor` works well for chained method calls

- src/main/java/org/openrewrite/staticanalysis/EqualsAvoidsNullVisitor.java
- src/main/java/org/openrewrite/staticanalysis/SimplifyBooleanExpression.java
> Collapse constitutionals in SimplifyBooleanExpression

- src/main/java/org/openrewrite/staticanalysis/CatchClauseOnlyRethrows.java
- src/main/java/org/openrewrite/staticanalysis/FinalizePrivateFields.java
- src/main/java/org/openrewrite/staticanalysis/csharp/CSharpFileChecker.java
- src/main/java/org/openrewrite/staticanalysis/csharp/package-info.java
- Fixes #437
- Following on from https://github.com/openrewrite/rewrite-static-analysis/pull/411
> Guard against missing Cs class now that dependency is provided

- src/main/resources/META-INF/rewrite/java-best-practices.yml
- src/test/java/org/openrewrite/staticanalysis/ReplaceApacheCommonsLang3ValidateNotNullWithObjectsRequireNonNullTest.java
- Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/457
> Replace `Validate.notNull(String)` as well

- src/main/java/org/openrewrite/staticanalysis/EqualsAvoidsNull.java
- src/test/java/org/openrewrite/staticanalysis/EqualsAvoidsNullTest.java
this is last one. The lombok stuff is working now. 👍
> fix missing ObjectEquals

- src/main/java/org/openrewrite/staticanalysis/RemoveSystemOutPrintln.java
Applying automated code suggestions.
To address the following comments in unrelated PRs:
```
src/main/java/org/openrewrite/staticanalysis/RemoveSystemOutPrintln.java
lines 19-19
```
> Fixing imports

- src/test/java/org/openrewrite/staticanalysis/EqualsAvoidsNullTest.java
Minor change. Adding newline character in one of the tests.
Fix:
```
src/test/java/org/openrewrite/staticanalysis/EqualsAvoidsNullTest.java
lines 70-70
```
code suggestion.
> Code suggestions - java source code indented

- src/main/java/org/openrewrite/staticanalysis/NoDoubleBraceInitialization.java
- src/test/java/org/openrewrite/staticanalysis/NoDoubleBraceInitializationTest.java
- fixed issue https://github.com/openrewrite/rewrite-static-analysis/issues/356
- added tests
> Fix missing constructor argument issue

- src/main/java/org/openrewrite/staticanalysis/AnnotateNullableMethods.java
Added spaces to description
@timtebeek
> Added spaces

- src/main/java/org/openrewrite/staticanalysis/LowercasePackage.java
- src/main/java/org/openrewrite/staticanalysis/ReplaceStackWithDeque.java
https://github.com/openrewrite/rewrite/pull/5282
> Revert option for literal visiting in ChangePackage/ChangeType

- src/main/java/org/openrewrite/staticanalysis/DefaultComesLastVisitor.java
- src/test/java/org/openrewrite/staticanalysis/DefaultComesLastTest.java
Reimplemented logic in DefaultComesLast Visitor
The code now assumes every case is a fall through case, best case scenario it falls through 0 times.
It handles the bug correctly.
- Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/4
> DefaultComesLast should correctly support fall through cases

- src/main/java/org/openrewrite/staticanalysis/ExplicitInitializationVisitor.java
- src/test/java/org/openrewrite/staticanalysis/ExplicitInitializationTest.java
add support for anonymous classes for `ExplicitInitialization` recipe 
https://github.com/openrewrite/rewrite-static-analysis/issues/109
> Enhance ExplicitInitialization to handle anonymous classes

- src/main/java/org/openrewrite/staticanalysis/InstanceOfPatternMatch.java
- src/test/java/org/openrewrite/staticanalysis/InstanceOfPatternMatchTest.java
- fix https://github.com/openrewrite/rewrite-static-analysis/issues/532
> Fix type substitution for `var` variable

- src/test/java/org/openrewrite/staticanalysis/MissingOverrideAnnotationTest.java
Adds a new unit test case.
To prove that #178 is already fixed.
> Add cloneInInterface test case to MissingOverrideAnnotationTest

- src/main/java/org/openrewrite/staticanalysis/CustomImportOrder.java
- src/main/java/org/openrewrite/staticanalysis/CustomImportOrderVisitor.java
- src/main/resources/META-INF/rewrite/common-static-analysis.yml
- src/main/resources/META-INF/rewrite/static-analysis.yml
- src/test/java/org/openrewrite/staticanalysis/CustomImportOrderRecipeTest.java
Added CustomImportOrder recipe
Dependant pull request  - https://github.com/openrewrite/rewrite/pull/5381
> CustomImportOrder recipe

- src/main/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReference.java
- src/test/java/org/openrewrite/staticanalysis/ReplaceLambdaWithMethodReferenceTest.java
> No MethodReference for parentheses

- src/main/java/org/openrewrite/staticanalysis/ReorderAnnotations.java
- src/test/java/org/openrewrite/staticanalysis/ReorderAnnotationsTest.java
- Follow up from https://github.com/openrewrite/rewrite-static-analysis/pull/544#issuecomment-2976148831
> There's one change here that I'm not quite happy with, and was helpfully pointed out here:
- https://github.com/openrewrite/rewrite-static-analysis/issues/543#issuecomment-2855819351
> Order type annotations last

- src/test/java/org/openrewrite/staticanalysis/MinimumSwitchCasesTest.java
- Added a unit test for this issue: https://github.com/openrewrite/rewrite-static-analysis/issues/284
While exploring this issue: https://github.com/openrewrite/rewrite-static-analysis/issues/284, I realized that the issue is working fine now, so just added a test case for sanity and coverage.
@timtebeek
> Added unit test for minimum switch cases with bitwise operation.

- .claude/settings.local.json
- src/main/java/org/openrewrite/staticanalysis/SimplifyArraysAsList.java
- src/main/resources/META-INF/rewrite/common-static-analysis.yml
- src/test/java/org/openrewrite/staticanalysis/SimplifyArraysAsListTest.java
- Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/627
> Simplify `Arrays.asList` with new array argument

- src/main/java/org/openrewrite/staticanalysis/RemoveExtraSemicolons.java
Applying code suggestions.
Avoid noise in unrelated PRs:
```
src/main/java/org/openrewrite/staticanalysis/RemoveExtraSemicolons.java
lines 66-66
```
> Applying code suggestions

- src/main/java/org/openrewrite/staticanalysis/MoveConditionsToWhile.java
- src/main/resources/META-INF/rewrite/common-static-analysis.yml
- src/test/java/org/openrewrite/staticanalysis/MoveConditionsToWhileTest.java
A new recipe `MoveConditionsToWhile`.
- fixes #610
> `MoveConditionsToWhile` recipe

- src/main/java/org/openrewrite/staticanalysis/RemoveRedundantNullCheckBeforeLiteralEquals.java
- src/main/resources/META-INF/rewrite/common-static-analysis.yml
- src/test/java/org/openrewrite/staticanalysis/RemoveRedundantNullCheckBeforeLiteralEqualsTest.java
- Mirrors https://github.com/openrewrite/rewrite-static-analysis/pull/632
> Add `RemoveRedundantNullCheckBeforeLiteralEquals`

- src/main/java/org/openrewrite/staticanalysis/UseCollectionInterfaces.java
- src/test/java/org/openrewrite/staticanalysis/UseCollectionInterfacesTest.java
- Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/710
> Expand coverage of UseCollectionInterfaces to LinkedList, Stack, TreeMap, TreeSet and PriorityQueue

- src/main/resources/META-INF/rewrite/examples.yml
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.recipes.rewrite.OpenRewriteRecipeBestPractices?organizationId=QUxML09wZW4gU291cmNlL09wZW5SZXdyaXRl
> OpenRewrite recipe best practices

- src/main/resources/META-INF/rewrite/examples.yml
- src/test/java/org/openrewrite/staticanalysis/CombineSemanticallyEqualCatchBlocksTest.java
- src/test/java/org/openrewrite/staticanalysis/CompareEnumsWithEqualityOperatorTest.java
- src/test/java/org/openrewrite/staticanalysis/MethodNameCasingTest.java
- src/test/java/org/openrewrite/staticanalysis/RemoveInstanceOfPatternMatchTest.java
- src/test/java/org/openrewrite/staticanalysis/ReplaceDeprecatedRuntimeExecMethodsTest.java
- src/test/java/org/openrewrite/staticanalysis/UseAsBuilderTest.java
- src/test/java/org/openrewrite/staticanalysis/kotlin/ReplaceLambdaWithMethodReferenceTest.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.recipes.rewrite.OpenRewriteRecipeBestPractices?organizationId=ODQ2MGExMTUtNDg0My00N2EwLTgzMGMtNGE1NGExMTBmZDkw
> Update recipe documentation examples
